# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'benjominiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for benjominiOS
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
end
